#!/bin/bash


# ------------------------------------------------------------------------------
# | File System                                                                |
# ------------------------------------------------------------------------------




# ------------------------------------------------------------------------------
# | Search                                                                     |
# ------------------------------------------------------------------------------

# Search History
qh() {
    #           ┌─ enable colors for pipe
    #           │  ("--color=auto" enables colors only if
    #           │  the output is in the terminal)
    grep --color=always "$*" "$HISTFILE" |       less -RX
    # display ANSI color escape sequences in raw form ─┘│
    #       don't clear the screen after quitting less ─┘
}

# Search for text within the current directory
qt() {
    grep -ir --color=always "$*" . | less -RX
    #     │└─ search all files under each directory, recursively
    #     └─ ignore case
}